#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Not using echo, because it conflicts with AppArmor.
#echo "INFO $BASH_SOURCE: Dummy Tor."

exit 0
